force-app/main/default/objects/Deal_Review__c/Deal_Review__c.object-meta.xml
<CustomObject>
    <label>Deal Review</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Review__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Reviews</relationshipLabel>
    <relationshipName>Deal_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DealReviewHandlerClass.cls
public with sharing class DealReviewHandlerClass {

    /*
        on closed won opportunities, share the deal review records with the manager of the opportunity owner. 
    */
    public static void DealReview(List<Opportunity> closedWonOpps, Map<Id, Opportunity> oldOppMap) {

        Set<Id> oppIds = new Set<Id>();
        Set<Id> ownerIds = new Set<Id>();
        if(!closedWonOpps.isEmpty()){
            for(Opportunity newOpp : closedWonOpps){
                Opportunity opp = new Opportunity();
                if(oldOppMap != null){
                    opp = oldOppMap.get(newOpp.Id);

                    if(opp.StageName != 'Closed Won' && newOpp.StageName == 'Closed Won'){

                        oppIds.add(newOpp.Id);

                        ownerIds.add(newOpp.OwnerId);
                    }
                }
            }
        }
        List<Deal_Review__Share> shareList = new List<Deal_Review__Share>();
        if(!oppIds.isEmpty()){
            List<Deal_Review__c> reviewList = [select Id, Opportunity__c, Opportunity__r.OwnerId from Deal_Review__c where Opportunity__c IN :oppIds];

            Map<Id, Id> ownerToManagerMap = new Map<Id, Id>();

            List<User> userList = [Select Id, ManagerId From User where Id In : ownerIds ];

            For(User u : userList){
                ownerToManagerMap.put(u.Id, u.ManagerId);
            }

            for (Deal_Review__c dr : reviewList){
                Id managerId = ownerToManagerMap.get(dr.Opportunity__r.OwnerId);
                Deal_Review__Share drs = new Deal_Review__Share();
                drs.ParentId = dr.Id;
                drs.UserOrGroupId = managerId;
                drs.AccessLevel = 'Read';
                
                shareList.add(drs);
            }
        }

        if(!shareList.isEmpty()){
            insert shareList;
        }
    }
}