force-app/main/default/objects/Bed__c/Bed__c.object-meta.xml
<CustomObject>
    <label>Bed</label>
    <nameField>
        <displayFormat>BED-{0}</displayFormat>
        <label>Bed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bed__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Admission_Status__c.field-meta.xml
<CustomField>
    <fullName>Admission_Status__c</fullName>
    <label>Admission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admitted</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>In Treatment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bed</label>
    <referenceTo>Bed__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Waiting_List__c/Waiting_List__c.object-meta.xml
<CustomObject>
    <label>Waiting List</label>
    <nameField>
        <displayFormat>WL-{0}</displayFormat>
        <label>Waiting List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiting Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Waiting_List__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Waiting_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Waiting for Bed</fullName>
            </value>
            <value>
                <fullName>Patient Admitted</fullName>
            </value>
            <value>
                <fullName>Bed Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BedHandlerClass.cls
public with sharing class BedHandlerClass {
    public static void assignBedsToPatients(List<Bed__c> bedList){

        List<Patient__c> waitingListPatients = [Select Id, Priority__c, Admission_Status__c, Bed__c From Patient__c where Admission_Status__c = 'Waiting'];

        Map<String, List<Patient__c>> priorityMap = new Map<String, List<Patient__c>>();

        priorityMap.put('Critical', new List<Patient__c>());
        priorityMap.put('Emergency', new List<Patient__c>());
        priorityMap.put('Normal', new List<Patient__c>());

        for(Patient__c patient : waitingListPatients){
            if(priorityMap.containsKey(patient.Priority__c)){
                priorityMap.get(patient.Priority__c).add(patient);
            }
        }

        List<Patient__c> sortedPatients = new List<Patient__c>();

        for(String priority : new List<String>{'Critical', 'Emergency', 'Normal'}){
            sortedPatients.addAll(priorityMap.get(priority));
        }
        Set<Id> patientIds = new Set<Id>();
        for(Patient__c patient : sortedPatients){
            patientIds.add(patient.Id);
        }

        List<Waiting_List__c> waitingListRecords = [Select Id, Patient__c From Waiting_List__c where Patient__c in : patientIds];

        Map<Id, Waiting_List__c> waitingListMap = new Map<Id, Waiting_List__c>();

        for(Waiting_List__c waitingList : waitingListRecords){
            waitingListMap.put(waitingList.Patient__c, waitingList);
        }
        List<Patient__c> patientsToUpdate = new List<Patient__c>();
        List<Bed__c> bedsToUpdate = new List<Bed__c>();
        List<Waiting_List__c> waitingListToDelete = new List<Waiting_List__c>();
        for(Bed__c bed : bedList){
            if(!sortedPatients.isEmpty()){
                Patient__c patientToAssign = sortedPatients.remove(0);
                patientToAssign.Admission_Status__c = 'Admitted';
                patientToAssign.Bed__c = bed.Id;
                patientsToUpdate.add(patientToAssign);

                Bed__c bedToUpdate = new Bed__c(Id = bed.Id);
                bedToUpdate.Status__c = 'Occupied';
                bedsToUpdate.add(bedToUpdate);

                Waiting_List__c waitingRecords = waitingListMap.get(patientToAssign.Id);
                waitingListToDelete.add(waitingRecords);
            }
        }

        if(!patientsToUpdate.isEmpty()){
            update patientsToUpdate;
        }
        if(!bedsToUpdate.isEmpty()){
            update bedsToUpdate;
        }

        if(!waitingListToDelete.isEmpty()){
            delete waitingListToDelete;
        }
    }
}