force-app/main/default/objects/Bed__c/Bed__c.object-meta.xml
<CustomObject>
    <label>Bed</label>
    <nameField>
        <displayFormat>BED-{0}</displayFormat>
        <label>Bed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bed__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bed__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Admission_Status__c.field-meta.xml
<CustomField>
    <fullName>Admission_Status__c</fullName>
    <label>Admission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admitted</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>In Treatment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bed</label>
    <referenceTo>Bed__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Waiting_List__c/Waiting_List__c.object-meta.xml
<CustomObject>
    <label>Waiting List</label>
    <nameField>
        <displayFormat>WL-{0}</displayFormat>
        <label>Waiting List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiting Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Waiting_List__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Waiting Lists</relationshipLabel>
    <relationshipName>Waiting_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Waiting_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Waiting for Bed</fullName>
            </value>
            <value>
                <fullName>Patient Admitted</fullName>
            </value>
            <value>
                <fullName>Bed Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PatientHandlerClass.cls
public with sharing class PatientHandlerClass {
    private static Map<String, List<Bed__c>> getAvailableBed(String category){
        List<Bed__c> beds = [Select Id, Category__c, Status__c From Bed__c where Status__c = 'Available' and Category__c = : category];
        Map<String, List<Bed__c>> bedMap = new Map<String, List<Bed__c>>();
        if(!beds.isEmpty()){
           for(Bed__c b : beds){
               if(!bedMap.containsKey(b.Category__c)){
                   bedMap.put(b.Category__c, new List<Bed__c>());
               }
               bedMap.get(b.Category__c).add(b);
           }
        }
        return bedMap;
    }
    
    public static void allocateBed(List<Patient__c> patients){

        List<Patient__c> updatedPatients = new List<Patient__c>();
        List<Bed__c> bedsToUpdate = new List<Bed__c>();
        List<Waiting_List__c> waitingListToInsert = new List<Waiting_List__c>();
        if(!patients.isEmpty()){
            for(Patient__c p : patients){
                if(p.Admission_Status__c != 'Waiting') continue;

                String patientPriority = p.Priority__c;
                Bed__c allocateBed = null;

                Map<String, List<Bed__c>> availableBeds = getAvailableBed(patientPriority);

                if(availableBeds.containsKey(patientPriority)){
                    List<Bed__c> bedsPriority = availableBeds.get(patientPriority);

                    if(!bedsPriority.isEmpty()){
                        allocateBed = bedsPriority.remove(0);
                    }
                }
                if(allocateBed != null){
                    Patient__c updatedPatient = new Patient__c(Id = p.Id, Bed__c = allocateBed.Id, Admission_Status__c = 'Admitted');
                    updatedPatients.add(updatedPatient);

                    allocateBed.Status__c = 'Occupied';
                    bedsToUpdate.add(allocateBed);
                }else{
                    Waiting_List__c waitingListRecord = new Waiting_List__c();
                    waitingListRecord.Patient__c = p.id;
                    waitingListRecord.Status__c = 'Waiting for Bed';
                    waitingListToInsert.add(waitingListRecord);
                }
            }
        }

        if(!bedsToUpdate.isEmpty()){
            update bedsToUpdate;
        }

        if(!waitingListToInsert.isEmpty()){
            insert waitingListToInsert;
        }

        if(!updatedPatients.isEmpty()){
            update updatedPatients;
        }
    }
}